[package]
name = "email_newsletter_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "email_newsletter_api"

[dependencies]
actix-web = "4.5.1"
reqwest = "0.12.2"
tokio = { version = "1.36.0", features = ["full"] }
